- name: build and push to docker
  uses: docker/build-push-action@v2
  with:
    push: true
    tags: ${{github.sha}}
  env:
    DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
    DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
