on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Debug - List files
        run: ls -al

      - name: Debug - List Docker images before build
        run: docker images

      - name: build and push to docker
        uses: docker/build-push-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{github.sha}}

      - name: Debug - List Docker images after build
        run: docker images
