on:
  push:
    branches:
      - main

name: Build and Push Docker Image

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Ruta al contexto del Dockerfile
        file: ./path/to/Dockerfile  # Ruta al Dockerfile
        platforms: linux/amd64,linux/arm64  # Plataformas objetivo (ajusta según tus necesidades)
        push: true
        tags: |
          user/repo:latest
          user/repo:${{ github.sha }}
        labels: |
          org.opencontainers.image.title=user/repo
